### ISSUE TITLE
Problem deleting an entry from related post

### ISSUE THREAD

**Issue by ttillberg** [hereswhatidid/acf-2way-pr#1]
I'm experiencing the following error when I want to delete an entry from a related post (using the v5 of ACF).

`Catchable fatal error: Object of class WP_Post could not be converted to string in /wp-content/plugins/acf-2way-pr/acf-2way-pr-v5.php on line 138`

It appears that `$existing_values` contains `WP_Post_Objects` whereas `array($post_id)` contains `strings`.
I'm using the `post_object` setting for the field value, and I believe the comparison wouldn't fail if I was to select `ID`s ?

**Comment by hereswhatidid** [comment]
Thanks for the find.  I hope to have this resolved in the next push.
