### ISSUE TITLE
Error when saving post when using "Post Objects"

### ISSUE THREAD

**Issue by marktoce** [hereswhatidid/acf-2way-pr#3]
When I use "Post IDs" I have no issue saving an edit to a post. When I use "Post Objects" I make an edit on the post page and I get the following error:

Catchable fatal error: Object of class WP_Post could not be converted to string in /Applications/MAMP/htdocs/iisc/www/wp-content/plugins/acf-2way-pr/acf-2way-pr-v4.php on line 140

The post I am editing is a custom post type, and I am relating it to another post type. ACF Version 4.3.9

**Comment by hereswhatidid** [comment]
This has been fixed in 1.0.2
